name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print shahab faghat shahab dj
        run: ehco "shahab faghat shahab dj"
      - name: Print by by shahabdj
        run: ehco "by by shahabdj"
